import 'dotenv/config';
import crypto from 'node:crypto';
import { createClient } from '@supabase/supabase-js';
import express from 'express';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import { Client, EmbedBuilder, GatewayIntentBits, REST, Routes } from 'discord.js';

for (const key of ['SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY','BOT_TOKEN_ENCRYPTION_KEY']) {
  if (!process.env[key]) throw new Error(`Missing required server environment variable: ${key}`);
}
const encryptionKey=Buffer.from(process.env.BOT_TOKEN_ENCRYPTION_KEY,'base64');
if(encryptionKey.length!==32) throw new Error('BOT_TOKEN_ENCRYPTION_KEY must be a base64-encoded 32-byte key.');
const db=createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const app=express(), live=new Map();
app.disable('x-powered-by'); app.use(helmet()); app.use(express.json({limit:'256kb'}));
app.use('/api',rateLimit({windowMs:60000,limit:120,standardHeaders:'draft-7',legacyHeaders:false}));

function encryptSecret(text){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',encryptionKey,iv),enc=Buffer.concat([c.update(text,'utf8'),c.final()]);return [iv,c.getAuthTag(),enc].map(x=>x.toString('base64url')).join('.')}
function decryptSecret(text){const [i,t,e]=text.split('.'),d=crypto.createDecipheriv('aes-256-gcm',encryptionKey,Buffer.from(i,'base64url'));d.setAuthTag(Buffer.from(t,'base64url'));return Buffer.concat([d.update(Buffer.from(e,'base64url')),d.final()]).toString('utf8')}
async function auth(req,res,next){const h=req.get('authorization')||'',token=h.startsWith('Bearer ')?h.slice(7):'';if(!token)return res.status(401).json({error:'Sign in to continue.'});const {data,error}=await db.auth.getUser(token);if(error||!data?.user)return res.status(401).json({error:'Your session is no longer valid.'});req.user=data.user;next()}
app.get('/api/health',(_q,r)=>r.json({ok:true,runtime:'discord.js',onlineBots:live.size})); app.use('/api',auth);

async function owned(uid,id){const {data,error}=await db.from('bots').select('*').eq('id',id).eq('owner_id',uid).maybeSingle();if(error)throw error;if(!data)throw Object.assign(new Error('Bot not found.'),{status:404});return data}
async function status(uid,id,s,x={}){const {error}=await db.from('bot_status').upsert({bot_id:id,owner_id:uid,status:s,updated_at:new Date().toISOString(),...x},{onConflict:'bot_id'});if(error)throw error}
async function log(uid,id,level,message){await db.from('bot_logs').insert({owner_id:uid,bot_id:id,level,message:String(message).slice(0,2000)})}
async function clientBot(row){const {data:c,error}=await db.from('commands').select('*').eq('bot_id',row.id).eq('owner_id',row.owner_id);if(error)throw error;const ids=(c||[]).map(x=>x.id);const f=ids.length?await db.from('workflows').select('command_id,steps').in('command_id',ids).eq('owner_id',row.owner_id):{data:[]};const fm=new Map((f.data||[]).map(x=>[x.command_id,x.steps]));return {id:row.id,name:row.name,description:row.description,updatedAt:row.updated_at,discordUserID:row.discord_user_id,discordUsername:row.discord_username,discordGlobalName:row.discord_global_name,discordAvatarURL:row.discord_avatar_url,discordBannerURL:row.discord_banner_url,commands:(c||[]).map(x=>({id:x.id,name:x.name,trigger:x.trigger,response:x.response,description:x.description,isEnabled:x.enabled,actions:fm.get(x.id)||[]}))}}

async function save(uid,bot){
 if(!bot||!/^[0-9a-f-]{36}$/i.test(bot.id||''))throw Object.assign(new Error('Invalid bot data.'),{status:400});
 const row={id:bot.id,owner_id:uid,name:String(bot.name||'').trim().slice(0,100),description:String(bot.description||'').slice(0,2000),discord_user_id:String(bot.discordUserID||''),discord_username:String(bot.discordUsername||'').slice(0,100),discord_global_name:bot.discordGlobalName||null,discord_avatar_url:bot.discordAvatarURL||null,discord_banner_url:bot.discordBannerURL||null,updated_at:new Date().toISOString()};
 const {data:s,error}=await db.from('bots').upsert(row,{onConflict:'id'}).select().single();if(error)throw error;
 const old=await db.from('commands').select('id').eq('bot_id',s.id).eq('owner_id',uid),keep=new Set();
 for(const x of (bot.commands||[]).slice(0,100)){const id=/^[0-9a-f-]{36}$/i.test(x.id||'')?x.id:crypto.randomUUID(),name=String(x.name||'').toLowerCase().slice(0,32);if(!/^[a-z0-9_-]{1,32}$/.test(name))throw Object.assign(new Error('Invalid slash command name.'),{status:400});const cr={id,bot_id:s.id,owner_id:uid,name,trigger:String(x.trigger||'').slice(0,40),description:String(x.description||'Bot command').slice(0,100),response:String(x.response||'').slice(0,2000),enabled:Boolean(x.isEnabled),updated_at:new Date().toISOString()};let q=await db.from('commands').upsert(cr,{onConflict:'id'});if(q.error)throw q.error;q=await db.from('workflows').upsert({id,command_id:id,bot_id:s.id,owner_id:uid,steps:Array.isArray(x.actions)?x.actions.slice(0,40):[],updated_at:new Date().toISOString()},{onConflict:'command_id'});if(q.error)throw q.error;keep.add(id)}
 const del=(old.data||[]).map(x=>x.id).filter(id=>!keep.has(id));if(del.length)await db.from('commands').delete().in('id',del).eq('owner_id',uid);
 return clientBot(s);
}
function interpolate(v,i){return String(v||'').replace(/{{\s*user\s*}}/g,i.user?.username||'member').replace(/{{\s*server\s*}}/g,i.guild?.name||'').slice(0,2000)}
async function execute(rt,i,steps){for(const s of steps||[]){const a=interpolate(s.value,i),b=interpolate(s.secondaryValue,i);if(s.kind==='sendMessage')await i.editReply({content:a||' '});else if(s.kind==='embed')await i.editReply({embeds:[new EmbedBuilder().setTitle(a||' ').setDescription(b||' ')]});else if(['kick','ban','timeout','addRole','removeRole'].includes(s.kind)){if(!i.guild)throw new Error('This action requires a server.');const u=i.options.getUser('target');if(!u)throw new Error('Choose a target member.');const m=await i.guild.members.fetch(u.id);if(s.kind==='kick')await m.kick(a||undefined);if(s.kind==='ban')await i.guild.members.ban(u.id,{reason:a||undefined});if(s.kind==='timeout')await m.timeout(Math.min(Number(a)||600000,2419200000),b||undefined);if(s.kind==='addRole'||s.kind==='removeRole'){const role=i.guild.roles.cache.find(r=>r.id===a||r.name===a);if(!role)throw new Error('Role not found.');await m.roles[s.kind==='addRole'?'add':'remove'](role)}}}if(!i.replied&&!i.deferred)await i.reply({content:'Done.',ephemeral:true})}
async function register(rt){const {data,error}=await db.from('commands').select('id,name,description,enabled').eq('bot_id',rt.botId).eq('owner_id',rt.ownerId);if(error)throw error;const defs=(data||[]).filter(x=>x.enabled).map(x=>({name:x.name,description:(x.description||'Bot command').slice(0,100),type:1,options:[{type:6,name:'target',description:'Optional target member',required:false}]}));await new REST({version:'10'}).setToken(rt.token).put(Routes.applicationCommands(rt.applicationId),{body:defs})}
async function start(uid,id){const b=await owned(uid,id);if(live.has(id))return;const {data:s,error}=await db.from('bot_secrets').select('encrypted_token').eq('bot_id',id).eq('owner_id',uid).single();if(error||!s)throw Object.assign(new Error('No saved Discord credential.'),{status:409});const token=decryptSecret(s.encrypted_token),client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers]}),rt={botId:id,ownerId:uid,client,token,applicationId:b.discord_user_id,startedAt:Date.now()};live.set(id,rt);await status(uid,id,'starting');client.once('ready',async()=>{rt.applicationId=client.user.id;await register(rt);await status(uid,id,'online',{started_at:new Date().toISOString(),last_error:null});await log(uid,id,'info',`Bot is online as ${client.user.username}.`)});client.on('interactionCreate',async i=>{if(!i.isChatInputCommand())return;try{await i.deferReply({ephemeral:true});const {data:c}=await db.from('commands').select('id,enabled').eq('bot_id',id).eq('owner_id',uid).eq('name',i.commandName).maybeSingle();if(!c?.enabled)return i.editReply('This command is disabled.');const {data:f}=await db.from('workflows').select('steps').eq('command_id',c.id).eq('owner_id',uid).maybeSingle();await execute(rt,i,f?.steps||[])}catch(e){await i.editReply('That command could not be completed.').catch(()=>{});await log(uid,id,'error',e.message)}});try{await client.login(token)}catch(e){live.delete(id);client.destroy();await status(uid,id,'error',{last_error:e.message});throw Object.assign(new Error('Discord could not start this bot.'),{status:400})}}
async function stop(uid,id){await owned(uid,id);const rt=live.get(id);if(rt){live.delete(id);rt.client.destroy()}await status(uid,id,'offline',{last_seen_at:new Date().toISOString(),uptime_seconds:rt?Math.floor((Date.now()-rt.startedAt)/1000):0});await log(uid,id,'info','Bot stopped.')}

app.post('/api/discord/validate',async(q,r,n)=>{try{const t=String(q.body?.bot_token||'').trim(),x=await fetch('https://discord.com/api/v10/users/@me',{headers:{authorization:`Bot ${t}`},signal:AbortSignal.timeout(10000)});if(!x.ok)return r.status(401).json({error:'Discord did not accept this bot token.'});const p=await x.json();r.json({id:p.id,username:p.username,global_name:p.global_name||null,avatar:p.avatar||null,banner:p.banner||null})}catch(e){n(e)}});
app.get('/api/bots',async(q,r,n)=>{try{const {data,error}=await db.from('bots').select('*').eq('owner_id',q.user.id).order('created_at',{ascending:false});if(error)throw error;r.json({bots:await Promise.all((data||[]).map(clientBot))})}catch(e){n(e)}});
app.post('/api/bots',async(q,r,n)=>{try{const t=String(q.body?.bot_token||'').trim(),x=await fetch('https://discord.com/api/v10/users/@me',{headers:{authorization:`Bot ${t}`}});if(!x.ok)return r.status(401).json({error:'Invalid bot token.'});const p=await x.json();if(p.id!==String(q.body?.bot?.discordUserID||''))return r.status(400).json({error:'Verified bot does not match project.'});const bot=await save(q.user.id,q.body.bot);await db.from('bot_secrets').upsert({bot_id:bot.id,owner_id:q.user.id,encrypted_token:encryptSecret(t),updated_at:new Date().toISOString()},{onConflict:'bot_id'});await status(q.user.id,bot.id,'offline');r.status(201).json({bot})}catch(e){n(e)}});
app.put('/api/bots/:id',async(q,r,n)=>{try{await owned(q.user.id,q.params.id);r.json({bot:await save(q.user.id,q.body.bot)})}catch(e){n(e)}});
app.post('/api/bots/:id/action',async(q,r,n)=>{try{const a=q.body?.action;if(a==='start')await start(q.user.id,q.params.id);else if(a==='stop')await stop(q.user.id,q.params.id);else if(a==='restart'){await stop(q.user.id,q.params.id);await start(q.user.id,q.params.id)}else return r.status(400).json({error:'Unknown runtime action.'});await db.from('bots').update({desired_status:a==='stop'?'offline':'online'}).eq('id',q.params.id).eq('owner_id',q.user.id);r.json({status:a==='stop'?'offline':'online'})}catch(e){n(e)}});
app.get('/api/bots/:id/status',async(q,r,n)=>{try{await owned(q.user.id,q.params.id);const {data}=await db.from('bot_status').select('*').eq('bot_id',q.params.id).eq('owner_id',q.user.id).maybeSingle();r.json(data||{status:'offline'})}catch(e){n(e)}});
app.get('/api/bots/:id/logs',async(q,r,n)=>{try{await owned(q.user.id,q.params.id);const {data,error}=await db.from('bot_logs').select('id,level,message,created_at').eq('bot_id',q.params.id).eq('owner_id',q.user.id).order('created_at',{ascending:false}).limit(100);if(error)throw error;r.json({logs:data||[]})}catch(e){n(e)}});
app.delete('/api/bots/:id',async(q,r,n)=>{try{await stop(q.user.id,q.params.id);const {error}=await db.from('bots').delete().eq('id',q.params.id).eq('owner_id',q.user.id);if(error)throw error;r.json({deleted:true})}catch(e){n(e)}});
app.use((e,_q,r,_n)=>r.status(Number(e.status)||500).json({error:Number(e.status)>=400&&Number(e.status)<500?e.message:'The server could not complete that request.'}));

const port=Number(process.env.PORT||3000);
app.listen(port,'0.0.0.0',async()=>{console.log(`Discord runtime API listening on port ${port}`);const {data}=await db.from('bots').select('id,owner_id').eq('desired_status','online');for(const b of data||[])start(b.owner_id,b.id).catch(e=>console.error(e.message))});
process.on('SIGTERM',()=>{for(const r of live.values())r.client.destroy();process.exit(0)});
process.on('SIGINT',()=>{for(const r of live.values())r.client.destroy();process.exit(0)});
